# Generated by Django 4.2.5 on 2023-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_class',
            field=models.CharField(max_length=100),
        ),
    ]
